<div id="login-form">	
    <form class="cssform" id="form-login" action="<?php echo $this->baseUrl ?>/admin/login" method="post">
    	
    	<fieldset>
        	<legend><strong>Login</strong></legend>
    	    
    	    <label for="usuario">Usuario: </label>
    	    <input type="text" id="usuario" name="usuario" value="" size="20"/><br>
    	    
    	    <label for="password">Clave: </label>
    	    <input type="password" id="password" name="password" value="" size="20" /><br>
    	        
    	    <label for="kludge"></label>
    	    <input tabindex="5" type="submit" name="login" value="Entrar" onclick="login_validar();" />

        </fieldset>
    </form>
</div>

