<!-- CARGA JS definidos en config.ini -->
<?php echo $this->render('_core_javascript_load.phtml'); ?>

<!-- CARGA DINAMICA SEGUN EL MODULO ACTUALMENTE EN EJECUCION -->
<?php echo $this->render('_module_javascript_load.phtml'); ?>

<?php if( isset($this->scriptaculous) && $this->scriptaculous) :?>
    <script>google.load("prototype", "1.6");</script>
    <script>google.load("scriptaculous", "1.8.1");</script>
<?php endif; ?>