<?php if(isset($this->user->usuario_id) || isset($this->user->admin_id)):  ?>

    <ul id="menu_cabezal">
    
        <?php if (isset($this->layout()->menu) && count($this->layout()->menu) > 0 ): ?>

            <?php foreach($this->layout()->menu as $item => $menu): ?>

                <li id="menu_item_home">
                    <a href="<?php echo $this->baseUrl ?>/<?php echo $menu['menu_url'] ?> ">
                        <strong><?php echo $menu['menu_texto'] ?> </strong>
                    </a>
                </li>

            <?php endforeach; ?>
            
        <?php endif; ?>
    
    </ul>
    
<?php endif; ?>