<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
<html>

	<head>
		<meta http-equiv="Content-Type" content="text/html; Charset=UTF-8" />
		<meta http-equiv="expires" content="Wed, 26 Feb 1997 08:21:57 GMT" />
		<meta http-equiv="pragma" content="no-cache" />
		<meta http-equiv="Cache-Control" content="no-cache" />
		<meta http-equiv="Content-Language" content="es-ES" />

        <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl;?>/styles/site.css" />
        <!-- <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl;?>/styles/thickbox.css" />-->
        <!-- <link rel="stylesheet" type="text/css" media="screen" href="<?php echo $this->baseUrl;?>/styles/facebox.css" />-->
        
        <script src="http://www.google.com/jsapi"></script>
        <script>google.load("jquery", "1.3");</script>
        <script>google.load("jqueryui", "1.5.3");</script>

        <!-- HERRAMIENTAS -->
        <!-- <script src="<?php echo $this->baseUrl;?>/scripts/thickbox-3.1.js" type="text/javascript"></script>-->
        <!-- <script src="<?php echo $this->baseUrl;?>/scripts/facebox.js" type="text/javascript"></script>-->

        <!-- GENERALES -->
        <script src="<?php echo $this->baseUrl;?>/scripts/site.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl;?>/scripts/site_tools.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl;?>/scripts/site_effects.js" type="text/javascript"></script>
        
        <!-- CARGA DINAMICA -->
        <?php echo $this->render('_module_javascript_load.phtml'); ?>
        <?php echo $this->render('_module_css_load.phtml'); ?>

        <!-- OPCIONALES -->
        <script src="<?php echo $this->baseUrl;?>/scripts/site_forms.js" type="text/javascript"></script>

        <?php if( isset($this->scriptaculous) && $this->scriptaculous) :?>
            <script>google.load("prototype", "1.6");</script>
            <script>google.load("scriptaculous", "1.8.1");</script>
        <?php endif; ?>

	</head>
	
<body>

  <div id="wrap">

    <div id="header-section">
        <img alt="logo" src="<?php echo $this->baseUrl;?>/images/logo.gif" border="0" />
    </div>

	 <!-- Navigation -->
     <?php if(isset($this->user->usuario)): ?>
        <strong>usuario</strong>&nbsp;<?php echo $this->user->usuario;?>&nbsp;&nbsp;
     <?php endif; ?>

    <div id="header">
        <?php echo $this->render('_menu_cabezal.phtml'); ?>
    </div>

    <div id="left-column">
        <?php echo $this->render('_menu_lateral.phtml'); ?>
    </div>

    <div id="right-column">
    </div>

    <div id="middle-column">

        <div>
            <?php if(!is_null($this->mensajeError)): ?>
                <?php echo $this->render('_box_error.phtml'); ?>
            <?php endif ?>
        </div>

        <h1><?php echo $this->placeholder('title') ?></h1>
        
		<?php echo $this->layout()->content ?>

	  <!-- FOOTER -->
    
  </div>
</body>
</html>