<?php if(isset($this->user->usuario_id)): ?>

    <ul id="menu_cabezal">
    
       <li id="menu_item_home"><a href="<?php echo $this->baseUrl; ?>/"><strong>home</strong></a></li>

        <?php if (isset($this->layout()->menu) && count($this->layout()->menu) > 0 ): ?>

            <?php foreach($this->layout()->menu as $item => $menu): ?>

                <li id="menu_item_home">
                    <a href="<?php echo $this->baseUrl ?>/<?php echo $menu['menu_url'] ?> ">
                        <strong><?php echo $menu['menu_texto'] ?> </strong>
                    </a>
                </li>

            <?php endforeach; ?>
            
        <?php endif; ?>

        <li id="menu_item_salir">
            <a href="<?php echo $this->baseUrl ?>/admin/login/logout">Salir</a>
        </li>
    
    </ul>
    
<?php endif; ?>