<?php
/* MODULE LOAD CSS
 *
 * Se encarga de buscar dentro del modulo corriente en ejecucion si tiene
 * un main.css, si existe, lo carga (permite poder configurar facilmente
 * la estetica de un modulo particular)
 */
$filename = realpath('..')  . DIRECTORY_SEPARATOR
    .'application'          . DIRECTORY_SEPARATOR
    .$this->moduleName      . DIRECTORY_SEPARATOR
    .'views'                . DIRECTORY_SEPARATOR
    .'scripts'              . DIRECTORY_SEPARATOR
    .$this->controllerName  . DIRECTORY_SEPARATOR
    .'main.css';

if(file_exists($filename)){

    $handle     = fopen($filename, "r");
    $contents   = fread($handle, filesize($filename));

    fclose($handle);

    $str_scripts = '<style type="text/css">'.$contents.'</style>';

    if($this->config->general->devel || $this->config->general->debug){
        echo $str_scripts;
    }else{
        /* "comprime" (elimina espacios) */
        echo preg_replace('/\s+/', ' ', $str_scripts);
    }    
}