<?php if($this->config->general->twitter != ''): ?>

    <div id="twitter_div">
        <h2 class="sidebar-title"><?php echo strtoupper($this->config->general->twitter) ?> Updates</h2>
        <ul id="twitter_update_list"></ul>
        <a href="http://twitter.com/<?php echo $this->config->general->twitter ?>"
           id="twitter-link"
           style="display:block;text-align:right;">sígueme a través de Twitter</a>
    </div>
    <script
        type="text/javascript"
        src="http://twitter.com/javascripts/blogger.js"></script>
    <script
        type="text/javascript"
        src="http://twitter.com/statuses/user_timeline/<?php echo $this->config->general->twitter ?>.json?callback=twitterCallback2&amp;count=5"></script>

    <script type="text/javascript">
        $(document).ready(
        function(){
            Nifty("div#twitter_div","big");
        }
    );
    </script>
<?php endif; ?>