<div id="login" class="login">
  <form action="<?php echo $this->baseUrl ?>/usuarios/login" method="post" id="login-form">
    <label><em>IP : </em> <strong><?php echo $_SERVER['REMOTE_ADDR'] ?></strong></label>
    <label><em>Usuario : </em><input id="usuario" type="text" name="usuario" /></label>
    <label><em>Clave : </em><input id="password" type="password" name="password" /></label>
    <input type="submit" class="submit" id="submit" value="Entrar" onclick="login_validar();" />
  </form>
</div>

<div id="box">
    <h1>¿Problemas con la clave?</h1>
    <p>Si eres un usuario registrado e intentas ingresar y el sistema no te lo permite,
    envíanos un email a <strong><?php echo $this->htmlEmailOfuscado($this->config->email->soporte) ?></strong> </p>   
</div>

<script>

    $(document).ready(
        function(){
            $("#usuario").focus();
              Nifty("div#box","big");
              Nifty("div#login","big");
        }
    );

</script>